common:
    TotalMoney: 1000000000
    TotalNum: 100000
    MinMoney: 1
    MaxMoney: 200
    MaxAmount: 5
    P: 0.5

Database:
    UserName: group7
    PassWord: rain@Group7
    DB_Name: envelop-rain
    MysqlAddr: rdsmysqlha6bc8291c2b53b0a.rds.ivolces.com:3306

Redis:
    RedisAddr: redis-cn0224c7295o6276z.redis.ivolces.com:6379
    RedisPassword: rain@Group7
    RedisPoolSize: 2000
# Database:
#     UserName: root
#     PassWord: Rothyu980908
#     DB_Name: envelop-rain
#     MysqlAddr: localhost:3306

# Redis:
#     RedisAddr: localhost:6379
#     RedisPassword: 
#     RedisPoolSize: 100

Limiter:
    SnatchPerSecond: 50000
    OpenPerSecond: 20000
    WalletPerSecond: 20000

Kafka:
    BrokerAddr: kafka-zpbvh1wawffzt3.cn-beijing.kafka-internal.ivolces.com:9092
    Topic: dbtest

# Kafka:
#     BrokerAddr: localhost:9092
#     Topic: dbtest7

Logger:
    LogPath: ./app.log