common:
    TotalMoney: 100000.0
    TotalNum: 1000
    MinMoney: 1.0
    MaxMoney: 200.0
    MaxAmount: 5
    P: 0.2

Database:
    UserName: group7
    PassWord: rain@Group7
    DB_Name: envelop-rain
    MysqlAddr: rdsmysqlha6bc8291c2b53b0a.rds.ivolces.com:3306

Redis:
    RedisAddr: redis-cn02ubqn3px4a2y7z.redis.ivolces.com:6379
    RedisPassword: rain@Group7
    RedisPoolSize: 1000