common:
    TotalMoney: 100000
    TotalNum: 1000
    MinMoney: 1
    MaxMoney: 200
    MaxAmount: 5
    P: 0.7

Database:
    UserName: root
    PassWord:
    DB_Name: envelop
    MysqlAddr: 127.0.0.1:3306

Redis:
    RedisAddr: 127.0.0.1:6379
    RedisPassword: 
    RedisPoolSize: 100

Limiter:
    SnatchPerSecond: 1000
    OpenPerMinute: 1000
    WalletPerMinute: 1000