common:
    TotalMoney: 100000000
    TotalNum: 100000
    MinMoney: 1
    MaxMoney: 2000
    MaxAmount: 5
    P: 0.7

# Database:
#     UserName: group7
#     PassWord: rain@Group7
#     DB_Name: envelop-rain
#     MysqlAddr: rdsmysqlha6bc8291c2b53b0a.rds.ivolces.com:3306

# Redis:
#     RedisAddr: redis-cn02ubqn3px4a2y7z.redis.ivolces.com:6379
#     RedisPassword: rain@Group7
#     RedisPoolSize: 1000
Database:
    UserName: root
    PassWord: Rothyu980908
    DB_Name: envelop-rain
    MysqlAddr: localhost:3306

Redis:
    RedisAddr: localhost:6379
    RedisPassword: 
    RedisPoolSize: 100

Limiter:
    SnatchPerSecond: 20000
    OpenPerMinute: 10000
    WalletPerMinute: 10000

Kafka:
    BrokerAddr: localhost:9092
    Topic: testdb